apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: xqq445vay-python 
  janus-idp.io/tekton: xqq445vay-python
  backstage.io/kubernetes-id: xqq445vay-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: xqq445vay-python
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml