apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: xqq445vay-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: xqq445vay-python 
  name: xqq445vay-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: xqq445vay-python 
